[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NODE_VERSION = "18.20.6"
  NPM_FLAGS = "--legacy-peer-deps --force"
  NETLIFY_USE_NPM = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/projects/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000" 